@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoiYWRtaW4iLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNTY1MjgyMTU2LCJleHAiOjE1NjUyODU3NTZ9.UxvCNR08m6thb0oigojQy7e8FNtgGYi2QQ14y4GAocM
@token2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJuYW1lIjoiaXZlbnMiLCJyb2xlIjoidXNlciJ9LCJpYXQiOjE1NjUyODI0MjQsImV4cCI6MTU2NTI4NjAyNH0.3snJuUdZzAhEN5MvCEKhJvSncM2SP_wSSPLEJJsHIiU
# Create User
POST {{baseUrl}}/user HTTP/1.1
Content-Type: application/json
Accept: application/json

{
	"username": "ivens",
	"email": "email@user.com",
	"password": "123456"
}

###
# Login
POST {{baseUrl}}/auth HTTP/1.1
Content-Type: application/json
Accept: application/json

{
	"email": "admin@admin.com",
	"password": "admin"
}

###
# Get all users
GET {{baseUrl}}/admin HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}
